listen=YES
listen_ipv6=NO
anonymous_enable=YES
anon_root=/var/ftp
local_enable=NO
write_enable=NO
no_anon_password=YES
anon_world_readable_only=YES
dirmessage_enable=YES
xferlog_enable=YES
seccomp_sandbox=NO
secure_chroot_dir=/var/run/vsftpd/empty
pasv_enable=YES
pasv_min_port=21100
pasv_max_port=21110
pasv_address=127.0.0.1
ftpd_banner=nexus-edge FTP service (vsftpd 2.3.4)
